### PR TITLE
Activate high-res splash page background image on high-density screens

### LINKED ISSUE #335: Retina city-photo.jpg images aren't being used on high-density screens
As far as I can tell, the high-density images aren't being used.

Looking at some references/documentation, it seems like an easy fix. 

#### How to Implement

Example implementation (out of date?) https://gist.github.com/marcedwards/3446599

(Simpler example, and more recent. Might miss some browsers, though. Also goes through a fairly exhaustive list of "outdated" examples that might actually be helpful: https://css-tricks.com/snippets/css/retina-display-media-query/ )

A blogger at W3C says to use the webkit-device-pixel-ratio and min-resolution media query properties. https://www.w3.org/blog/CSS/2012/06/14/unprefix-webkit-device-pixel-ratio/ #

#### Which Browsers Support Which CSS Properties?

Browser support for these CSS properties: http://caniuse.com/#feat=css-media-resolution

My actual tests confirm what caniuse.com says: https://gist.github.com/DeeDeeG/cae2743ecdf6e34420427eb33f0e745f

#### Debugging/testing resource

Thingy to tell you what your browser's current CSS dpi/min-device-pixel-ratio/min-resolution is, etc.: http://bjango.com/articles/min-device-pixel-ratio/

### PR DESCRIPTION
**Pull request by DeeDeeG**
Devices with standard "1x" density will still get the less-detailed image.

Right now only city-photo.jpg (the splash page image)
has high-res alternate versions.

# Context
- Fixes #335 

# Summary of Changes

- screens with 2x or greater (but less than 3x) density get the [city-photo-2x.jpg](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/app/assets/images/city-photo-2x.jpg) asset
- screens with 3x or greater density get the [city-photo-3x.jpg](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/app/assets/images/city-photo-3x.jpg) asset

# Checklist

- [x] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots

### CODE REVIEW

**Comment by mi-wood** [comment]
Each of these increases in size by a factor of 4. The splash page load times aren't great already. It'd be nice to go the other direction in download size since the image resolution isn't critical to the application.

**Comment by DeeDeeG** [comment]
I did think the filesizes were a bit large, so I made compressed
versions of the assets. Not on GitHub anywhere yet, but on my machine,
here are how the original assets compare with the new compressed ones:

city-photo.jpg
- 321 KB, 1600 x 804 (original)
    - 322 KB, 2038 x 1024 (slightly improved visual quality and shows
up better on tall screens, due to higher resolution)

city-photo-2x.jpg
- 1.03 MB, 3200 x 1608 (original)
    - 694 KB, 3758 x 1888 (better resolution, similar or better detail
due to higher res + and moderate compression)

city-photo-3x.jpg
- 4.24 MB, 7516 x 3777 (original)
    - vs. choice of:
        - 1.82 MB, 7516 x 3777 (some banding in the blue sky, high quality)
        - 2.14 MB, 7516 x 3777 (less banding, some slight texture improvement)
        - 2.53 MB, 7516 x 3777 (very high quality, still a bit of
banding in sky, but not much)
        - 2.83 MB, 7516 x 3777 (very high quality, not a big
difference from source)

I would like to upload at minimum the new city-photo.jpg for your
consideration, and perhaps we can also activate the 2x image if we are
still being moderately conservative. Of course, I leave the call to
activate them at all to the core maintainers.

**Comment by DeeDeeG** [comment]
### New compressed assets comparison (click to enlarge)
#### City-photo.jpg
##### Original (321 KB)
city-photo
##### New (322 KB, higher resolution) (+1 KB, but looks nicer on tall screens)
87-jpegtran-fastcrush
#### City-photo-2x.jpg
##### Original (1.03 MB)
city-photo-2x
##### New (694 KB, higher resolution) (-336 KB, looks better I think?)
80-jpegtran-fastcrush
#### City-photo-3x.jpg
##### Original (4.24 MB)
city-photo-3x
##### New (2.14 MB) (one of several options, we can compress more if subtle banding in the sky is alright) (This version saves 2.1 MB, almost 50% filesize savings)
77-jpegtran-fastcrush

**Comment by tkwidmer** [comment]
Lets go ahead and upload the compressed versions. I'm fine with that.

**Comment by DeeDeeG** [comment]
Full disclosure: I learned how to compress jpegs for the first time working on this. I found out afterward that I had been doing a compression technique that can add little bits of noise, like on the dome (see below): 

It's to the point where I think some of the originals are nicer-looking. I'd like to try to see what I can get without using that noise-inducing technique, and still using compression. Might get better results. 

I can...

- try re-working them, and then finish this PR with the best ones,
- commit these as-is, merge, then do the re-work in a separate PR,
- Just go with these as-is and be done.

Before:
before-crop

After:
after-crop

**Comment by mi-wood** [comment]
> 
    try re-working them, and then finish this PR with the best ones,
    commit these as-is, merge, then do the re-work in a separate PR,
    Just go with these as-is and be done.

I'll trust your opinion on how they look to you. If you think this is ready to merge, I'm happy to go ahead and do that.

**Comment by DeeDeeG** [comment]
Open to any opinions on these of course, but they're small, and look pretty nice. I'm pretty happy with them now.

Thanks for waiting!

**Pull request merged**
