### PR TITLE
Feature/lang folders

### PR DESCRIPTION
**Pull request by Intimaria**
# Context
- Referenced: #396 and #413 
- creates language folder structure for ease of adding new translations 

# Summary of Changes

- adds language specific folders within locale *for now just en*
- adds english language files to "en" folder

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Hi again, and thanks for this Pull Request.

If you don't mind, we should have fewer commits in this Pull Request. See this link for which commits are currently included in the PR: https://github.com/RefugeRestrooms/refugerestrooms/pull/422/commits,
or what changes are included: https://github.com/RefugeRestrooms/refugerestrooms/pull/422/files

---

The easy way to have fewer commits is to clone refuge into a new folder:

`git clone https://github.com/refugerestrooms/refugerestrooms [new-refuge-folder-name-here]`

And do the commits for this PR in the new folder.

---

A more-complicated way to have fewer commits in this PR:

From the folder you have been working in, we need to set up a clean develop branch that matches the upstream develop branch.

- `git checkout develop`
  - (Switch to your local copy of the `develop` branch)
- `git branch working-branch` 
  - (Copies your branch `develop` over to a branch called `working-branch`.) 
  - (This does not switch you to be on `working-branch`, so you are still on `develop`.)

Make an entry in the list of "remotes" so we can get the latest updates of github.com/refugerestrooms/refugerestrooms
- `git remote add upstream https://github.com/refugerestrooms/refugerestrooms`
- `git fetch upstream`
  - (Get latest updates from `upstream`.)
- `git reset --hard upstream/develop`
  - (Reset current branch to exactly match `develop` from upstream)

Then branch off of `develop` again to keep `develop` easily sync-able:
- `git branch new-feature` && `git checkout new-feature` . . . or the equivalent:
  -  `git checkout -b new-feature`

And now the `new-feature` branch can be used to finish the required work for this PR.

---

In any case, to push the local branch you're working on to this PR, and overwrite what's here now, you can do:
- `git push -f https://github.com/Intimaria/refugerestrooms feature/lang_folders`

**Comment by Intimaria** [comment]
Hi @DeeDeeG  I think I did it.

**Comment by DeeDeeG** [comment]
Okay, this looks good!

I would be happy to merge this. Just to be sure, are there any second opinions, @mi-wood, @tkwidmer?

**Comment by tkwidmer** [comment]
This looks good to me.

**Pull request merged**
