### PR TITLE
Hotfix/patreon update

### LINKED ISSUE #397: Add a Link to Patreon
We have a Patreon, but we don't link to it anywhere from the site. We should fix that. 
This is a perfect entry level item for somebody to take on.

https://www.patreon.com/refugerestrooms

### PR DESCRIPTION
**Pull request by KurtPrice**
# Context
- Fixes #397 
- A patreon account exists, but there is no link found on the site.

# Summary of Changes

- Added a brief blurb and link to the patreon account to _footer.html.haml

### CODE REVIEW

**Comment by tkwidmer** [comment]
I commented on the issue @KurtPrice, with a recommendation about adding a more visable button to the home page. And once you do that, i'll get this merged.

Thanks so much @KurtPrice

**Comment by KurtPrice** [comment]
Sounds good, I'll work on adding that. This is my first ruby project.

**Comment by tkwidmer** [comment]
If you merge develop, I made a change that makes the footer more readable: https://github.com/RefugeRestrooms/refugerestrooms/pull/403

**Comment by tkwidmer** [comment]
looks like the image itself needs to be commited into the `assets/images` directory

**Comment by KurtPrice** [comment]
Wow, I don't know how I failed to commit that. I will merge in develop and add that image for sure this time.

**Comment by tkwidmer** [comment]
Last comment, I promise. 

can you update the code to the following

```haml
   .row.even-more-headroom
     .col-xs-6.col-sm-3.col-sm-offset-3
       = link_to image_tag("app-store.svg", role: "img"), "https://itunes.apple.com/us/app/refuge-restrooms/id968531953?mt=8"
     .col-xs-6.col-sm-3.col-sm-offset-3
        = link_to image_tag("play-store.png"), "https://play.google.com/store/apps/details?id=org.refugerestrooms"
   .row.more-headroom.splash-bottom-padding
     .col-xs-12.col-sm-6.col-sm-offset-3
      = link_to image_tag("patreon.png"), "https://patreon.com/refugerestrooms"
```

With this implementation the app store and play store logos will show up side by side, with the patreon link below them. 

Thanks so much for your work on this!

**Comment by KurtPrice** [comment]
Yes I will do that right now!

**Comment by KurtPrice** [comment]
Finished the last changes.

**Comment by tkwidmer** [comment]
Specs are now failing, which seems unrelated. Code looks good to me.

**Comment by tkwidmer** [comment]
I'm restarting the build, since the Cucumber tests sometimes fail intermittently

**Comment by KurtPrice** [comment]
Awesome, thanks for the help, I was worried about what was causing it to fail. It looks pretty good to me!

**Comment by tkwidmer** [comment]
@KurtPrice no problem. I noticed the problem, and figured I could just fix the issue instead of bothering you since i had said earlier it was going to be my last comment. ^.^ Thanks for contributing!

**Pull request merged**
