### PR TITLE
100% FILIPINO TRANSLATION FOR devise.fl.yml FILE

### PR DESCRIPTION
**Pull request by vinzruzell**
Hi. This is my complete translation for devise.fl.yml file with 59 strings.

# Context
I have translated 100% for devise.en.yml to devise.fil.yml (Filipino Words).

# Summary of Changes
100% translation from 1-59 strings.

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots

## After
# Context
I have translated devise.en.yml to devise.fil.yml (Filipino Words).

# Summary of Changes
Completely translated 60 lines of devise.en.yml into Filipino language.

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots

## Before
image

## After
image

### CODE REVIEW

**Comment by vinzruzell** [comment]
HI. @DeeDeeG Pls. review my 100% filipino translation for devise.fl.yml file.

**Comment by DeeDeeG** [comment]
Thank you for this.

I have a couple of small comments, but we can merge this as soon as they are addressed.

**Comment by DeeDeeG** [comment]
Whoops, I replied to the wrong Pull Request.

Closing this, because the file isn't in the `config/locales/fil` folder, and we have a Pull Request already that has the file in that folder.

**Comment by vinzruzell** [comment]
Do.I need to resend changes?

**Pull request closed without merging**
