### PR TITLE
Created en.fil.yml

### PR DESCRIPTION
**Pull request by hnarasaki**
I believe this file will not be translated

# Context
Filipino Translation https://github.com/RefugeRestrooms/refugerestrooms/issues/451 

# Summary of Changes

Added file.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Hi again, @hnarasaki.

Generally we would prefer to accept all of these changes all together, in a single pull request.

Here are some steps to make these changes on one branch so they can be in a single pull request:
- You may visit your fork of Refuge Restrooms: https://github.com/hnarasaki/refugerestrooms
- There is a button to switch branches:
branches_button_with_arrow
- You may visit an existing branch such as `patch-1` or `Filipino-Staging`
  - You may optionally "branch off" (make a copy with a new name) of any branch by visiting the branch you want to copy, and then typing a new branch name in the dropdown menu of the "branch" button.
- While visiting the branch you want to work on, you may click on any file, where you will find the edit button.
- When you are finished editing, at the bottom of the screen you may select "Commit directly to the `[current]` branch. "
commit_directly_with_arrow
- You may then visit the main page of your fork again, and visit the branch with all of your Filipino translation files and changes on it.
- There is a "Pull request" button:
pull_request_with_arrow

**Comment by DeeDeeG** [comment]
As an alternative, we can merge each of these pull requests into a new branch at our repo, probably something like "Filipino-Staging-hnarasaki", until all the files are added/translated. Then we can review all the work and merge that into our main branch.

We're pretty flexible about it, so if one of these options works much better for you we can go with either strategy.

**Comment by DeeDeeG** [comment]
I believe putting all the changes relevant to a given issue into one branch, and then starting a single pull request for all the changes, is the typical way on GitHub. But we would rather accept the contribution as several pull requests than insist on receiving them any particular way.

(I hope the step-by-step instructions I put together above are okay, as I couldn't think of better way to express what we are looking for.)

I will wait until hearing back from you (or else a day or so if we don't hear back from you) before merging these pull requests as-is.

Thanks again for working on this.

**Comment by DeeDeeG** [comment]
Okay, I am merging these pull requests. :+1:

**Comment by DeeDeeG** [comment]
We do not need the file "en.yml" so I will close this pull request.

**Comment by hnarasaki** [comment]
@DeeDeeG Thanks for the explanation on this, it was helpful and I really appreciate it! :)

**Pull request closed without merging**
