### PR TITLE
Updated Swagger

### PR DESCRIPTION
**Pull request by btyy77c**
# Context
- Installed Swagger using webpack and removed the html/js/css from the public folder.

# Summary of Changes
- Deleted files from the public folder
- Install Swagger using Yarn
- Added Route, Controller, View, and JS to run Swagger

WARNING: Since I updated swagger, the classes changed and the css is no longer valid.  I added some basic CSS but the swagger layout is completely different now. 

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots

### CODE REVIEW

**Comment by DeeDeeG** [comment]
@btyy77c, Thanks for this! I'll test this in just a moment and see if this works on my machine.

**Comment by DeeDeeG** [comment]
As an aside again: It looks like thesee commits have some difference in their author info vs your GitHub account info. So they might not be attributed to your account.

We can go in and change that before merging if you like as mentioned before. We would need to figure out what address is the correct one, though. I believe you can find the email address(es) associated with you GitHub account at https://github.com/settings/emails . 

For more email privacy, you can also use the email address that looks like `[github-username]@users.noreply.github.com` Or `[7digits]+[github-username]@users.noreply.github.som` if your account was created after a certain date.

> [Note](https://help.github.com/articles/about-commit-email-addresses/): If you created your GitHub account after July 18, 2017, your GitHub-provided no-reply email address is a seven-digit ID number and your username in the form of ID+username@users.noreply.github.com. If you created your GitHub account prior to July 18, 2017, your GitHub-provided no-reply email address is your username in the form of username@users.noreply.github.com. You can get an ID-based GitHub-provided no-reply email address by selecting (or deselecting and reselecting) Keep my email address private in your email settings.

More info: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by DeeDeeG** [comment]
This looks pretty good!

[Link to screenshot](https://user-images.githubusercontent.com/20157115/46577138-fd896d00-c9ac-11e8-8c35-42fc09c84826.png).


The CSS does need a bit of updating, sure, but it's functional.

Unrelatedly, and unfortunately, my Docker instance still isn't loading any restroom entries from `db/export.csv`, so this is hard to test unless you manually submit a new restroom during testing.

I'm not sure if we should allow the `POST` method at this time, would want feedback from @mi-wood or @tkwidmer. But if we get API submission functionality for free by doing that, we would eventually want to enable it (after making sure we have good spam filtering I suppose.)

All-around, my impression is that it's better to have this as a nodejs dependency than pasted into the repo as html/css/js files. So I'd personally be happy to merge once we're finished reviewing and perhaps polishing the appearance and/or tweaking the configs a bit.

**Comment by DeeDeeG** [comment]
I have a pull request that makes it easier to test this sort of thing: #508

**Comment by tkwidmer** [comment]
Overall this looks really great to me. My only concern is adding a POST, although this is something we obviously want to do. I don't want to end up polluting the db with a lot of random requests.

**Comment by btyy77c** [comment]
> Overall this looks really great to me. My only concern is adding a POST, although this is something we obviously want to do. I don't want to end up polluting the db with a lot of random requests.

Can you help me understand where you are seeing the new `POST` action?  No POST action was added from this branch.  It's possible it's showing you a POST action already available in production, but I'm not seeing any POSTs when I view the page.  Thanks!

**Comment by DeeDeeG** [comment]
My apologies for the mixup, I can see now that POST is not functionally new in this pull request.

> Can you help me understand where you are seeing the new POST action?

When you make a request, the new docs interface exposes what methods are allowed:

new interface showing allowed methods, including GET POST and OPTIONS

(The old interface coincidentally didn't show that info.)

> No POST action was added from this branch. It's possible it's showing you a POST action already available in production [. . .] .

Yep. That's what happened. (Whoops.)

Conclusion: If we want to discuss or address the fact we appear to (already, regardless of this pull request) allow POST through the API, I think we can move that discussion out of this pull request.

I'd also like to do some work on the CSS, and maybe even consider the older version of the package; This isn't powering the underlying API backend, just the documentation interface (front end). If the older package was more user-friendly, we may as well go with that, barring any security patches that may have been added. Will look into this when I get time. (I'm sort of taking the day off, but wanted to respond to this.)

Thanks for pointing that out.

Best,

\-DeeDeeG

**Comment by DeeDeeG** [comment]
I'd like to try out the 2.x branch of this node package,since that'smore similar to whatwewere using before, and I just personally liked how the older interface looked.

Another possibility to look at is the `swagger-ui-dist` node package, which might be more of a pre-packaged deal with better styling? I think of doing this mostly because I can surmise we were using the "dist" approach before this pull request.

After looking into those things, I should have a pretty clear idea of what our options are, and hopefully can describe what the best choice is. I'm not likely to have time to do this right away, so if we need to make a quicker decision I'll try to come up with something faster. 

(We could also merge as-is and go back and improve it later if we just want to merge sooner and fix it up later. Or we could merge into a topic branch here and finish it up on that branch, I guess.)

**Comment by DeeDeeG** [comment]
For reference, `swagger-ui` and `swagger-ui-dist` with no custom CSS both look exactly like this:

Swagger UI API documentation with default, bare-bones placeholder styling

**Comment by DeeDeeG** [comment]
2.x branch of `swagger-ui` can't be used since we need to update Grape whenever we can (this pull request is set to do that)... BUT `swagger-ui` 2.x does not support recent Grape versions.

We have to move to Grape 1.1 or higher. And with that we will need at least `swagger-ui` 3.x

**Comment by DeeDeeG** [comment]
I think we can/should merge this as-is and do any fixups we need later. It would be nice to have up-to-date Grape and Swagger-UI.

(CSS tweaks or tweaks to the API code could come later if we want. But neither of those is strictly needed, they're just nice-to-haves.)

**Comment by DeeDeeG** [comment]
Would like to finally merge this soon.

I have a work-in-progress branch that fixes up the CSS to mostly match the visual style of the 2.x branch of swagger-ui.

But it would be great to have this merged. Particularly since it upgrades grape.

---

Would want to co-ordinate with Android team on this. Want to make sure this will not change the `.json` output of the API. We don't want to go breaking the apps!

(cc @hissingpanda, @Carmen-Git-It)

**Comment by DeeDeeG** [comment]
Merging so we can test the mobile apps against the develop branch auto-updating Heroku instance: https://refuge-staging-14.herokuapp.com/

**Pull request merged**
