### PR TITLE
100% completed for restroom.fil.yml file 

### PR DESCRIPTION
**Pull request by vinzruzell**
# Context
Hi this is my translation for restroom.en.yml file which translated into restroom.fil.yml filipino translation.

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots

## Before
image
## After
image

### CODE REVIEW

**Comment by vinzruzell** [comment]
HI @DeeDeeG pls look at this commit if you have time. Thank you.

**Comment by vinzruzell** [comment]
HI @DeeDeeG pls review this commit if you have time. Thank you.

**Comment by DeeDeeG** [comment]
Whoops, I thought I commented on this already.

This file looks good. Can it be moved to this folder?: `config/locales/fil/`

Thanks.

**Comment by vinzruzell** [comment]
Hi.. Sorry for that. I have already move to other folder.
Locale/fil/restroom.fil.yml

On Feb 25, 2018 4:14 AM, "DeeDeeG" <notifications@github.com> wrote:

Whoops, I thought I commented on this already.

This file looks good. Can it be moved to this folder?: config/locales/fil/

Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RefugeRestrooms/refugerestrooms/pull/467#issuecomment-368256578>,
or mute the thread

**Pull request merged**
