### PR TITLE
Potential UX fix to issue #264.

### PR DESCRIPTION
**Pull request by CullenIO**
Adds a message to tell the user it is searching by location.

### CODE REVIEW

**Comment by mi-wood** [comment]
I'd personally be in favor of a label vs using placeholder fields. There's much more liberty to be descriptive and it's permanent. Something like "Search by location (defaults to current location)". I don't think we're constricted with screen real estate or anything

**Comment by mi-wood** [comment]
Also, sorry for the slow reply!

**Comment by tkwidmer** [comment]
Yeah i'd prefer to use a label or a placeholder, but either of those would be wonderful! Thanks for this!

**Comment by mi-wood** [comment]
@CullenIO Do you have plans to fix this up or should we close this for now?

**Comment by mi-wood** [comment]
Going to close this for now, since it's been awhile

**Comment by DeeDeeG** [comment]
(I notice this is closed, but this still might be something we could accept, since there are no merge conflicts last I checked.)

Alright, here's what this looks like for now (screen recording):

https://gfycat.com/FocusedMiserlyIlladopsis

Is there anything that should still be changed? 
- Should the search button have some text in it to explain what it will do?
- Label placed elsewhere?

**Comment by tkwidmer** [comment]
I think the consensus was that we would rather this be a placeholder or a label vs changing the value of the field and putting this in as a value? @DeeDeeG

**Comment by DeeDeeG** [comment]
I think I get what you're saying. It shouldn't end up in the search box as something users would accidentally submit. Correct me if I'm wrong.

FWIW, I'm clicking around, and I'm finding that it's just about impossible to accidentally search for the text "Searching by current location..." (I can't select it, I even tried to copy and paste it but when I try to select it, it kind of disappears and is replaced with light grey "Enter a query". It doesn't go through even when manually typed??)

The one placeholder in that box I've managed to get as a search, by accident, was "1 Embarcadero Center, San Francisco, CA ...etc..." but I can't figure out how to do it reliably.

**Pull request closed without merging**
