### PR TITLE
add contributing doc for syncing repo with vagrant

### PR DESCRIPTION
**Pull request by mi-wood**
This PR adds some clarity around syncing the repo to vagrant and using the shell wrapper. Committing `.rake_tasks` because I think it should be the same for everyone and actually take awhile to generate...

### CODE REVIEW

**Comment by mi-wood** [comment]
removing `.rake_tasks`. Didn't realize it's from a zsh plugin not rake.

**Comment by mi-wood** [comment]
closes https://github.com/RefugeRestrooms/refugerestrooms/issues/299

**Comment by tkwidmer** [comment]
Looks good to me, @mi-wood is there any way to get rsync-auto to work just when you run vagrant up? To make it easier for folks?

**Comment by mi-wood** [comment]
@tkwidmer I looked into and it seems like the answer is no :( I'll keep an eye out for a solution though

**Comment by tkwidmer** [comment]
ok, gtg, lets get this merged!

**Pull request merged**
