### PR TITLE
Filipino Translation 

### PR DESCRIPTION
**Pull request by vinzruzell**
# Context
The proposed translation is from English language into Filipino language. For this translation I completed the whole file which is (about.en.yml) under config/locales.

# Summary of Changes

I translated the project config/locales/en/about.en.yml (English) into config/locales/fil/about.fil.yml (Filipino Language)
'en' in the file has been changed to 'fil'

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots
screenshot_20180215-062723

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Basically, the test system we use is broken, your translations are good. We can review your translations even if the tests fail. 

(The tests are automated and have a lot of moving parts. Sometimes one of those parts fails. This is one of those times.)

I'm also copying this reply from another Pull Request (https://github.com/RefugeRestrooms/refugerestrooms/pull/454#issuecomment-365708781), since I'm not sure if you saw it:

---

Thank you for submitting these translations.

The files you added look fine. Travis CI testing is showing errors in the pull requests you submitted, but I don't think the errors are caused by anything you did.

The errors all look similar to this:

```
      Timed out waiting for response to {"id":"1613a367-d27d-469a-b8f2-8c340f41f972","name":"visible","args":[2,0]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
```

Our simulated web browser that tests our webpage is having problems. We will have to try and figure out why that's happening, but I don't think it should hold up merging these files.

---

Eventually we hope to have the actual translations reviewed by another person or two who are fluent in Filipino.

**Comment by vinzruzell** [comment]
Pls. Review. Thanks :)

**Comment by mi-wood** [comment]
Hi @vinzruzell could you try to translate the rest of the files? If only a few of them are translated, then the user is going to get a half translated application.

**Comment by vinzruzell** [comment]
Okay. I will finish translating the file. Thank you :)

**Comment by vinzruzell** [comment]
I would like to ask also if your system checking is already fixed? So that
my translations will be reviewed :) thank you :)

**Comment by DeeDeeG** [comment]
We are looking into the problem, but in the mean-time, I'd recommend ignoring the test system.

The test system does not test translations yet. There usually is no useful data in the results for translation PRs. We can ignore the test system and still review your translations manually.

We can, and would, accept and merge your translations without the test system passing.

We are a volunteer team, so this work is done in our spare time. Manually reviewing your Pull Request is easier than fixing the tests, and we are happy to manually review this Pull Request any time. We have to review manually anyway, even if the tests _do_ pass, because the tests don't notice every issue. So the test system being broken is not a problem for this Pull Request.

**Comment by vinzruzell** [comment]
Thank you for that information :)

**Comment by DeeDeeG** [comment]
I am closing this Pull Request, since we have already accepted/merged `about.fil.yml`, and we are reviewing `devise.fil.yml` in #454.

**Pull request closed without merging**
