### PR TITLE
Downgrade grape + grape-swagger to fix url issues

### LINKED ISSUE #203: Cannot access API at http://www.refugerestrooms.org/api/docs/
When I head to the API link, I get this error:

*Unable to read api 'restrooms' from path http://www.refugerestrooms.org/api/swagger_doc.json/restrooms.json (server returned undefined)*

### PR DESCRIPTION
**Pull request by kiesia**
Fixes #203. I'm not super familiar with the API or grape, so please double check that all is still working.

### CODE REVIEW

**Comment by tkwidmer** [comment]
Seems fine to me. As long as its showing up on the docs page it should be fine.

**Comment by hkellaway** [comment]
Im unfortunately still getting the error

**Comment by cllns** [comment]
It looks like it's only been merged into `develop`, not `master`.

In general, changes to `develop` should be reflected on `http://refugestaging.herokuapp.com` but it seems like `/api/` is not a part of staging.

**Comment by tkwidmer** [comment]
I can do a release today to master.

**Pull request merged**
