### PR TITLE
CONTRIBUTING.md: Add more info and steps

### PR DESCRIPTION
**Pull request by DeeDeeG**
Clarifies and explains more of the CONTRIBUTING.md document.

# Context
- Decided to make this even clearer for beginners, especially after a brief discussion of this on Slack

# Summary of Changes

- Explains steps in the process with a bit more detail
- Adds a step to get a bash session going on the container.
- Adds links to the Wiki for RSpec and Capybara.

# Checklist

- [N/A] Tested Mobile Responsiveness
- [N/A] Added Unit Tests
- [x] CI Passes
- [Probably] Deploys to Heroku on test Correctly (Maintainers will handle)
- [x] Added Documentation (Service and Code when required)

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Open to discussion and changes to the working, but I wanted to make out contributing guide even clearer than before, particularly/especially for complete newcomers. 

Also wanted to particularly add the step `docker-compose run web bash` since I had no idea this could be done before asking if/how it could be done on our Slack.

**Comment by tkwidmer** [comment]
This looks good to me.

**Comment by tkwidmer** [comment]
Still LGTM

**Comment by DeeDeeG** [comment]
Okay, going to merge in a moment.

**Pull request merged**
