### PR TITLE
Release 1.10.0

### PR DESCRIPTION
**Pull request by tkwidmer**
Includes The following PRs
#383 @hectorsector AriaLabel for Screen Readers on Search and Search by Location
#389 @KurtPrice Patreon Button
#407 @DeeDeeG AriaLabel Unit Tests
#404 @DeeDeeG Vagrant Documentation
#403 @tkwidmer Fix footer being cut off
#391 @iforgotband Bump Bugsnag Version
#389 @stardust66  Fix for Vertical Align
#386 @DeeDeeG Navbar Brand Fix

Thanks everybody!

### CODE REVIEW

**Comment by tkwidmer** [comment]
https://refuge-staging-14-pr-408.herokuapp.com/restrooms/new

https://refuge-staging-14-pr-408.herokuapp.com/restrooms

both seem to be broken

**Comment by tkwidmer** [comment]
Raw staging seem to be working

https://refuge-staging-14.herokuapp.com/restrooms

**Comment by tkwidmer** [comment]
```
Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.6ms)

2017-12-28T02:10:54.703071+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d] Not notifying due to an invalid api_key

2017-12-28T02:10:54.703858+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]   

2017-12-28T02:10:54.703896+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d] ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "restrooms" does not exist

2017-12-28T02:10:54.703897+00:00 app[web.1]: LINE 8:                WHERE a.attrelid = '"restrooms"'::regclass

2017-12-28T02:10:54.703897+00:00 app[web.1]:                                           ^

2017-12-28T02:10:54.703898+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),

2017-12-28T02:10:54.703898+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,

2017-12-28T02:10:54.703899+00:00 app[web.1]:                      c.collname, col_description(a.attrelid, a.attnum) AS comment

2017-12-28T02:10:54.703902+00:00 app[web.1]:                 FROM pg_attribute a

2017-12-28T02:10:54.703902+00:00 app[web.1]:                 LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum

2017-12-28T02:10:54.703903+00:00 app[web.1]:                 LEFT JOIN pg_type t ON a.atttypid = t.oid

2017-12-28T02:10:54.703903+00:00 app[web.1]:                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation

2017-12-28T02:10:54.703904+00:00 app[web.1]:                WHERE a.attrelid = '"restrooms"'::regclass

2017-12-28T02:10:54.703904+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped

2017-12-28T02:10:54.703904+00:00 app[web.1]:                ORDER BY a.attnum

2017-12-28T02:10:54.703905+00:00 app[web.1]: ):

2017-12-28T02:10:54.704042+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]     24:   .row

2017-12-28T02:10:54.704043+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]     25:     .col-sm-12.headroom

2017-12-28T02:10:54.704043+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]     26:       #list.restrooms-list

2017-12-28T02:10:54.704044+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]     27:         = render @restrooms

2017-12-28T02:10:54.704044+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]     28:         = paginate @restrooms

2017-12-28T02:10:54.704044+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]     29: / .row

2017-12-28T02:10:54.704045+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]     30: /   .col-xs-12.headroom

2017-12-28T02:10:54.704053+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d]   

2017-12-28T02:10:54.704083+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d] app/views/restrooms/index.html.haml:27:in `_app_views_restrooms_index_html_haml__2111402162399667545_70025681927420'

2017-12-28T02:10:54.704084+00:00 app[web.1]: [a1da516b-124e-411c-afa2-24b142ae715d] app/controllers/restrooms_controller.rb:11:in `index'
```

**Comment by tkwidmer** [comment]
Looks like it may just be an issue with the Heroku deploy, redeploying. The database wasn't able to connect.

**Comment by DeeDeeG** [comment]
I can say: It works in Vagrant off of the current develop branch.

**Comment by tkwidmer** [comment]
Had to adjust the database on Heroku, something was wonky with the deploy. So we should be good.

Looks like it's functioning properly. 

https://refuge-staging-14-pr-408.herokuapp.com/

**Pull request merged**
