### PR TITLE
Add Italian translation

### LINKED ISSUE #517: Italian translation
## Scope / difficulty

Translation will be added in a dedicated subfolder in [config/locales](https://github.com/RefugeRestrooms/refugerestrooms/tree/develop/config/locales)

## Impact

Improved internationalisation.

## Rationale

Let the project be understandable even for italian people who don't know english language or any other Language currently available

## Proposal

Add the italian translation

## How to actually do this:

Translate all files inside [config/locales/en](https://github.com/RefugeRestrooms/refugerestrooms/tree/develop/config/locales/en)

### PR DESCRIPTION
**Pull request by MauroCoppola**
# Context
- Fixes #517 
- Add Italian translation

# Summary of Changes

- Create *it* directory inside config/locales/
- Translate all files inside *it* folder

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Thank you for this!

We will need to have another native speaker of Italian to review this properly, but when that happens, we will be happy to merge!

Happy Hacktoberfest! :jack_o_lantern: :computer: :fallen_leaf: :sparkles:

**Comment by DeeDeeG** [comment]
I notice this pull request has the branch `master` merged in.

I would recommend merging `develop` into this branch instead, since our recent development is all there in `develop`. (We then merge everything from `develop` into `master` all at once each time when we "deploy" changes to the website.)

I can leave this to you or I can do it, either is fine.

(I have made a backup branch of this pull request. I will leave the backup unchanged in case I accidentally merge something incorrectly: https://github.com/DeeDeeG/refugerestrooms/tree/translation-italian-backup)


Thanks again,
\-DeeDeeG

**Comment by MauroCoppola** [comment]
Hi, I updated the translation thanks to @bebora suggestions. For the consistency issues in _devise.it.yml_, I used [this file](https://github.com/tigrish/devise-i18n/blob/master/rails/locales/it.yml) as reference, where there is the same string for three different keys.

@DeeDeeG I only have to merge _develop_ branch into my branch?

**Comment by bebora** [comment]
@MauroCoppola the problem in *devise.it.yml* is using both "e-mail" and "email", I would use "email" everywhere as in https://github.com/tigrish/devise-i18n/blob/master/rails/locales/en.yml.

*text_msg.it.yml*:
Line 4, I would use "SMS" instead of "testo".

**Comment by DeeDeeG** [comment]
Thank you @bebora for the review!

**Comment by DeeDeeG** [comment]
> @DeeDeeG I only have to merge develop branch into my branch?

Actually this is optional.

But we should remove the merge of `master` branch... If you don't mind, I can do this since it's a little complicated.

Whoever does it, I'm suggesting these steps:

- Checkout `translation-italian` branch
  - `git checkout translation-italian`
- Make a backup version of this branch in case we mess up
  - `git branch [backup-branch-name-here] translation-italian`
- Reset `translation-italian` to the commit before merge of master
  - `git reset --hard 1fb7c15`
- Grab the "fix typos" commit from the backup branch
  - `git cherry-pick 1da9fcd`
- Grab the "Fix consistency issues" commit
  - `git cherry-pick 1acfc10`

Optional:
- merge `develop` branch into `translation-italian`
  - `git merge develop`

Thanks again for doing this translation!

**Comment by DeeDeeG** [comment]
I made another backup branch in case anything goes wrong: https://github.com/DeeDeeG/refugerestrooms/commits/translation-italian-backup-2

**Comment by DeeDeeG** [comment]
We are hopefully going to delete `devise.[locale].yml` from our project and use the translations at https://github.com/tigrish/devise-i18n directly at some point. If either of you wants to submit a change there to replace "e-mail" with "email", it could help other people.

If you'd rather not, and if you don't mind me adding it [there](https://github.com/tigrish/devise-i18n/blob/master/rails/locales/it.yml), I can do that and give @bebora credit for noticing this.

Thanks.

**Comment by bebora** [comment]
Thanks for the suggestion, I sent a pull request there to update the it.yml locale.

**Comment by DeeDeeG** [comment]
I will go ahead and update this branch.

The old branch is still available at my fork: https://github.com/DeeDeeG/refugerestrooms/commits/translation-italian-backup-2

**Comment by DeeDeeG** [comment]
## Screenshots
### Before
Refuge Restrooms homepage in English

### After
Refuge Restrooms homepage in Italian

**Comment by DeeDeeG** [comment]
Thank you both, this is ready to merge! :tada:

**Pull request merged**
