### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by tbroadley**
# Summary of Changes
Fixes a few typos in the documentation.

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [x] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Seems as though this is merged into master, so develop doesn't have it.

**Comment by tbroadley** [comment]
Sorry, I guess I created the PR against the wrong branch. Would you like me to create another one against `develop`?

**Comment by tkwidmer** [comment]
@tbroadley yeah can you open one against develop really quick. I missed that.

**Comment by tbroadley** [comment]
@tkwidmer Sure, see #409.

**Pull request merged**
