### PR TITLE
add wiki to README

### PR DESCRIPTION
**Pull request by mi-wood**
Closes https://github.com/RefugeRestrooms/refugerestrooms/issues/321

### CODE REVIEW

**Comment by DeeDeeG** [comment]
I dig it, generally.

Wiki before CONTRIBUTING.md makes logical sense.

Would like to look it over and think more about phrasing before merging this, if that's okay. I came up with the sentence explaining what the Wiki is about in under a minute, but README.md gets a lot of eyeballs on it, so worth extra consideration, I think. Thanks for making this a PR!

**Comment by tkwidmer** [comment]
This looks good to me.

**Comment by DeeDeeG** [comment]
Hi, I came up with soime [alternative text](https://github.com/RefugeRestrooms/refugerestrooms/compare/wiki...DeeDeeG:wiki), but I'm really not sure which is better.

> +For more information on how to contribute to Refuge Restrooms, or how the technology works, see the [Wiki](https://github.com/RefugeRestrooms/refugerestrooms/wiki).
> +
> +To test your changes to Refuge Restrooms before before deploying them to the web, see [`CONTRIBUTING.md`](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/CONTRIBUTING.md)

Compare vs.:

> +For more information on how the technology powering Refuge Restrooms works, or how to get started from scratch, see the [Wiki](https://github.com/RefugeRestrooms/refugerestrooms/wiki).
> +
> +If you just want to get your environment setup for making changes locally and testing, you can head directly to the [`CONTRIBUTING.md`](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/CONTRIBUTING.md).

Thoughts/preferences?

**Comment by DeeDeeG** [comment]
Whoops, I think I pushed to the upstream branch instead of my local branch by mistake.

@mi-wood, if you still have your commits for this somewhere, you might want to force-push to this branch?

Otherwise, the whole added content of your commit was quoted in this comment: https://github.com/RefugeRestrooms/refugerestrooms/pull/436#issuecomment-363474782

FWIW I think this might be the best text:

> ```
> For more information on how to contribute to Refuge Restrooms, or how the technology works, see the [Wiki](https://github.com/RefugeRestrooms/refugerestrooms/wiki).
> 
> If you just want to get your environment set up for making changes locally and testing, you can head directly to [`CONTRIBUTING.md`](https://github.com/RefugeRestrooms/ @refugerestrooms/blob/develop/CONTRIBUTING.md).
> ```

But I don't want to hold this PR up, and I defer to your judgment, @mi-wood @tkwidmer

**Comment by mi-wood** [comment]
I like that last quoted text you posted 👍 feel free to push and merge that

**Pull request merged**
