### PR TITLE
update about and business faq

### PR DESCRIPTION
**Pull request by mi-wood**
Turning https://github.com/RefugeRestrooms/refugerestrooms/issues/272 into haml

### CODE REVIEW

**Comment by mi-wood** [comment]
I think we could go for increasing the paragraph font size on these too. I think this requires creating a new class for the about page

**Comment by DeeDeeG** [comment]
Just looking over the code changes, and in vagrant, it all looks pretty good.

- minor issue: the business FAQ link isn't working in vagrant. I would suggest a relative path such as `/business_info` rather than `https://refugerestrooms.org/business_info` but just doing that change didn't fix it on my machine. ~~Might have to set something up in `config/routes.rb`?~~
  - ~~Umm, I'm face-palming a bit that I didn't figure this one out quicker...~~
    - Minor typo: The href to `business_info` in `locales/about.en.yml` is just missing an equals sign. e.g.: `href='so-and-so'`
  - I personally believe a relative URL is better so we can test these things in vagrant more easily.
  - applies to link to `about` page from `business_info` page as well

- Just pointing out: this would probably make a merge conflict for #413, so we should probably merge that first for simplicity's sake... Noting however that the new Business FAQ would be untranslated at that point.
  - Maybe we can get a Spanish translation of `business_info` in place in #413 while this PR is still being worked on?
  - Redo this PR on top of develop after #413 is merged for smooth sailing?
    - Alternatively, just open a new PR to translate `business_info`, then merge #413 and hypothetical `business_info` translation PR, re-do this PR on top of develop

- Paragraph text size being bumped up sounds fine once everything else is settled
  - Can help with that if desired

**Comment by mi-wood** [comment]
I tried to do a relative path but with the haml and locale files it was proving to be a pita so I just kinda gave up 😅

**Comment by DeeDeeG** [comment]
Yeah, it's more complicated than it probably should be. (That's computer tech in a nutshell for you?) :P

Here is what I came up with: https://github.com/DeeDeeG/refugerestrooms/commit/6c8d7e14907551c249b8e4de9f26965faca529c7

**Comment by mi-wood** [comment]
That works :) I was trying to use the rails link helpers which made it weird

**Comment by Intimaria** [comment]
OK. will have a look at this later & translate the new information.

**Comment by DeeDeeG** [comment]
I think we can merge this PR if we want to clean up the PRs list a bit.

Bumping paragraph size can be posted as an issue to get to eventually, so we don't forget. Might make for a `good-first-issue`. OR I can try to make time to add such a paragraph size bump to `about` and `business_info` in this PR before merging this. I'd like to see this merged though, since it's so simple and rather thoroughly discussed in #272.

(note: we have 9 open PRs in the queue, all filed within the past month and a half's time! Wow, are we popular! But yeah, it's piling up!)

**Comment by DeeDeeG** [comment]
I added a commit that bumps paragraph size. (Computes to "15.4px" rather than "14px".) Open to comments or suggestions about how to improve the implementation.

**Comment by DeeDeeG** [comment]
Glad this is merged! 

By the way, `business_info.en.yml` ended up outside of the `en` sub-folder of `config/locales`.

Happy to move it over or let you do so, @mi-wood.

**Pull request merged**
