### PR TITLE
Google accessibility audit

### PR DESCRIPTION
**Pull request by clado**
Hi! I ran the [google accessibility audit](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en) and fixed many of the issues it suggested.
Unfixed issues include the contrast ratios on `.btn-light-purple`, `.greenRating`, `.yellowRating`, and `redRating` elements with white text, and contrast ratios on the google maps suggestions (😕). I increased the font size on the buttons instead of changing the color, because I didn't want to mess with the colour scheme.

### CODE REVIEW

**Comment by mi-wood** [comment]
Hey @clado, thanks for the PR! Sorry it's taken so long to get to this. I'm going to try and make some time soon to take a look.

**Comment by clado** [comment]
It's no problem, @mi-wood! Thank you for looking. :)
You might want to take a special look at #145 to make sure I didn't reintroduce it, seeing as you solved the bug initially.

**Comment by tkwidmer** [comment]
Overall I think this looks good

**Comment by clado** [comment]
In light of the post about cleaning up old PRs, I have noticed that recent work has introduced conflicts to this branch. I intend to make it mergable, but I'm in the middle of a busy semester right now, and might not have time until May at the latest, if that's okay. The conflicts seem simple enough so hopefully I'll get time earlier.

**Comment by DeeDeeG** [comment]
I would like to see accessibility be top notch and all, so I would personally love to see this one merged. (I saw that @clado said they may not be available for some time, so I don't mean to rush anyone.)

A lot of these changes that came up as conflicts, should turn out to be renaming the files from css.scss to .scss, for one, but also a few other, not-so-huge changes here and there. CSS is one of my strong areas, (and I probably did most of the changes that caused merge conflicts other than renaming files, sorry!) so I am totally available as a reviewer/troubleshooter for this.

Also any changes I made that conflict with the goal of accessibility, I would lean toward undoing my changes. They were mostly cosmetic and had to do with adding spacing between elements, so I think it won't be a big issue on that front.

**Comment by clado** [comment]
Hey! I just wanted to pop in and say that I've (finally) started working on this again. Sorry for the wait!
In order to prevent myself from resolving merge conflicts in terrible ways, I've cut a new branch instead of trying to update this one, and I'll submit a new PR when I'm done with it.
@DeeDeeG I'm sure your changes were fine! Front end isn't necessarily my strong suit, so I'd love your review on the new pull request if you end up being available!

**Comment by DeeDeeG** [comment]
Hi, I took a look at this by running your branch in Vagrant. (By the way, I have an old iPad, and I turned on VoiceOver, which is Apple's screen reader, to practice navigating the site with a screen reader). I discovered I know less than I thought about how screen readers work... but I'm learning. Anyways, I have some initial feedback.

All the changes here look good. 👍 (I don't understand every little change, personally, but nothing seems broken or off in any way.)

But now that we're addressing these things, I'm wondering if we can't go further than what the audit suggests?

Basically, I'm noticing we are a little inconsistent in some places wrt screen reader accessibility. The main logo in the nav bar is currently read aloud as "slash ... visited ... link ... navigation ... landmark". Because it links to the root "/" of the site. I think that should have its own label to be read aloud.

(Whereas the words "Refuge Restrooms" next to the nav logo are read aloud as "Refuge Restrooms ... visited ... link".)

If anyone else wants to try this out with a screen reader, I highly recommend it. We could all presumably learn a lot about how to make the site more accessible in that regard. If desired, I can upload videos of trying to navigate the site with Apple's VoiceOver on the iPad.

In any case I should be available to review this any time, more or less. Thanks for the work so far!

**Comment by DeeDeeG** [comment]
Hi again.

I spent some time (okay a lot of time) figuring out the merge conflicts.

In any case, the results of my efforts are located here: https://github.com/DeeDeeG/refugerestrooms/tree/pr268-rebased-on-develop

This is equivalent to this PR, in terms of changes, but is as of writing, 100% merge-able.

Hope this helps!

**Comment by DeeDeeG** [comment]
I found a resource about accessibility that we might want to look into:
- http://webaim.org (a really thorough web accessibility group out of Utah State University)
- http://wave.webaim.org/ (Their accessibility auditing tool, much like the Google accessibility audit)
- https://webaim.org/projects/screenreadersurvey6/ (Survey of screen reader users, particularly what are the most commonly used screen readers, and what features on a website are most important to screen reader users/which features are not so important.)

**Comment by DeeDeeG** [comment]
Also, I spent a few minutes looking over the changed version of the site using Vagrant, (running off of my branch with the resolved merge conflicts). Seems reasonably usable with VoiceOver! Three fairly things I think we should change:

- I think we need some sort of indication of what the search bar buttons do, because right now VoiceOver just reads them aloud as "button". There's two of them (the "magnifying glass", and the "location arrow".) I guess "search", and "search by my location" would do.

- Also, the "Refuge Restrooms" text in the navbar is flowing over to two lines of text; I think its html "width" should be set (maybe as a style for `.navbar-brand`), and have it be wider than the text itself. Right now the width seems to be inhereted from the \<a> tag, which is 45x45px. It should be about 280px, or 16em.

- The App Store download button isn't focusable with VoiceOver, so it would be nice to make that focusable. Not sure how at the moment, but should be doable.

**Comment by DeeDeeG** [comment]
I wanted to leave more information here about the merge conflicts, just in case you prefer to address them yourself, @clado. I found this a particularly advanced/challenging thing to do, and learned a lot in the process. I wanted the information on how to do this to be available to anyone reading through this PR.

### Reasons for conflicts

- The main thing that caused merge conflicts for this PR, was a recent [rebase-y merge](https://github.com/RefugeRestrooms/refugerestrooms/pull/350). This seems to explain the 24 commits listed before your actual deliberate changes for this PR. (My suggestion here is to work around this, like it looks like you've already done, by starting fresh at the tip of develop. An alternative method would be to `git reset --hard [hash-of-commit-before-branches-diverge]`. and working from there, before merging from develop, or rebasing on top of develop.)

- The other major thing was a [reorganization](https://github.com/RefugeRestrooms/refugerestrooms/commit/a9e2fa76b57899f9340f89abf1aa5b7b56108b10) of the SCSS files. With this reorganization, all styles in `application.scss` were moved out to other files. For this PR, I believe all changes to `application.scss` end up in `stylesheets\components\common.scss` and `stylesheets\components.nav.scss`

(Relatedly, at some point every `[filename].css.scss` got the extension changed to `[filename].scss`).

------

### Extracting commits from this Pull Request

- My major technique for getting changes out of this PR in order to use them, was visiting each commit on GitHub, and adding `.patch` to the end of the URL. For example: https://github.com/RefugeRestrooms/refugerestrooms/commit/406f0e96b73352830ea24e21c7ba3fe8ee54e0dc.patch

Copying all that text, and pasting into a text editor, and saving as `[any-name].patch` gives a "patch" to apply with various git commands.

### Techniques for re-applying these commits

To apply these patch files, there are two main options:

- `git apply [--options] [filename.patch]` adds the changes to your working directory, or stages them, depending on your command line options. (particularly useful is the --3way flag to attempt an automatic 3-way merge if needed.) You can then review changes, make any required edits, then `git commit` the changes. As far as I know, this does not keep the original commit date or commit message. 

(note: I did not use the above method, personally. I prefer the one below.)

- `git am [-options] [filename.patch]` tries to fully apply the commit, including the original commit date and original commit message. (Particularly useful is the `--3way` option, which attempts an automatic three-way merge. Often succeeds, but if it doesn't, you can go in and fix the merged files manually, then type `git am --continue` to commit every staged change. -- i.e. commit the attempted automatic three-way merge, whichever way you resolved it, or with whatever additional fixes you've staged.)
  - This keeps the original commit date and commit message, unlike `git apply`.

I found having a visual text editor with code highlighting and git support built in to be very valuable for managing these merges. Basically, the only thing I know of that meets that description is [Atom](https://atom.io/). 
(To open the Git tab in Atom, go to `View`, and click `Toggle Git Tab`... Or press `Ctrl + Shift + 8`)

I sincerely hope this is helpful. I'd still love to see this merged, for sure. If there's anything else you need or if we can be of some help, please let us know. Best regards.

**Comment by mi-wood** [comment]
@clado and @DeeDeeG, sorry about the rebase nonsense. I had squash and merge set by default, which throws things off with having a staging and master branch. So I had to do some weird branch deleting to eventually get it to work again :(

I opened a new PR for the rebased branch and will create issues for @DeeDeeG's future suggestions

**Pull request closed without merging**
