### PR TITLE
add reviewed changes

### PR DESCRIPTION
**Pull request by mi-wood**
@Intimaria I had someone take a look at the translation and they made some changes. I've created this PR with a clone of your branch so you can look over their proposal.

### CODE REVIEW

**Comment by Intimaria** [comment]
Hi, I just looked over it - I’m really grateful, very good to have these changes as it sorts out a lot of small mistakes. I think there’s a two little things in “signs” - an extra word, which was left over in the correction, and the use of the @, which is not screen readable and is out of use because it still refers to binary (incorporates feminine a and masculine o), which is what the use of e hopes to avoid (todes vs tod@s). This is accepted usage in inclusive Spanish and I mentioned it briefly in #413. Very minor exception, everything else is fantastic and will do what you said asap!

**Comment by Intimaria** [comment]
Is it possible to merge this into Spanish (I don't seem to be able to do it). I'm happy to leave the @ or change it to e, whatever is best, and I have to remove a 'que' from signs but I can do that no probs after.

**Comment by DeeDeeG** [comment]
Hi,

@Intimaria, just so you know, if we merge this as it's set up now, the new commit would end up in an upstream branch, meaning it wouldn't be part of your Pull Request. in order to get this into your branch, you can get the commit a couple different ways. 

First, fetch your remote called "origin", or "upstream" (whichever points to the upstream refugerestrooms repo...)

- `git fetch origin`, or `git fetch upstream` (or both, just to be sure.)

Checkout your working branch for #427 ...

- `git checkout [branch-name]`

And either merge this commit:

- `git merge 19199bb`

Or if that goes wrong, you can cherry-pick the commit instead:

- `git cherry-pick 19199bb`

**Comment by Intimaria** [comment]
Hi, @DeeDeeG long time no see! Thank you again, I think I did it. 

I also imported the new-translation-ready files into my local `Spanish` branch. So I will incorporate translations for those too. I'd been away for a bit so I lost my way slightly, the thread of different possibilities becomes more and more complex, heh.

And, of course, I will add any new changes that come in into #427 as and when. Very exciting!

**Comment by mi-wood** [comment]
Closing now that these have been incorporated into the other branch

**Pull request closed without merging**
