### PR TITLE
update kaminari and active admin

### PR DESCRIPTION
**Pull request by mi-wood**
# Context
- The Active Admin Restroom view is broken right now because of an old Kaminari version

# Summary of Changes

- Update Kaminari (and Active Admin while we're here)

### CODE REVIEW

**Comment by mi-wood** [comment]
I knew this would break grape... I'll try to look at this later.

**Comment by mi-wood** [comment]
@DeeDeeG do you want an Active Admin account? This will allow you to approve edit proposals once this is fixed.

**Comment by DeeDeeG** [comment]
@mi-wood sure. I don't know how much time this tends to take, but I'd spend some time on it if I had access. 👍 Would also help me understand how our updates here on GitHub affect the admin views.

**Comment by DeeDeeG** [comment]
Not sure if it helps this Pull Request work, but we effectively have the Grape update planned in #506.

**Comment by DeeDeeG** [comment]
I think we just need to add the `kaminari-grape` gem, since that was moved out of the main `kaminari` gem in 1.0: https://github.com/kaminari/kaminari/blob/master/CHANGELOG.md#100

(Lots of good info here, in case anything else comes up.)

I'm trying to check this out myself, but I'm on Windows and my Linux VM is rather slow.

**Comment by DeeDeeG** [comment]
@mi-wood, if you get a chance to look at this pull request again, it might be working now that #537 is merged into it.

(I'm not sure how to log in to the admin interface, even locally in Docker. So I'm not able to test if this fixed the problem. But at least #537 made Travis tests pass again on this branch.)

**Comment by DeeDeeG** [comment]
In my personal Heroku deploys of `develop` and this branch, the admin page is still not working.

I see this error message:

https://gist.github.com/DeeDeeG/58035aaf235d6e2ddf055d1923d52441

**Pull request merged**
