### PR TITLE
public: Add French PDF signs.

### PR DESCRIPTION
**Pull request by juharris**
# Context
There are currently only PDF signs in English.

# Summary of Changes
Add French versions of the PDF signs. They're pretty close to the English ones.
Thanks for the help @Layla-ElAsri !

# Checklist

- [ ] Tested Mobile Responsiveness
- [ ] Added Unit Tests
- [ ] CI Passes
- [ ] Deploys to Heroku on test Correctly (Maintainers will handle)
- [ ] Added Documentation (Service and Code when required)

# Screenshots

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Hello, @juharris!

I will take a close look at this Pull Request soon.

Regards,

\-DeeDeeG

**Comment by DeeDeeG** [comment]
Hi again.

These PDFs look good. I have a pretty good idea of how these can be served when visiting the French localization of refugerestrooms.org as well, but that can be a separate Pull Request so it can be properly tested.

For now, I'd like to check with some other French speakers (hopefully at least one!) about the actual translation itself. If that goes well, we can merge these. Thank you once again!

**Comment by DeeDeeG** [comment]
Hi again, @BertrandClosset and @TiteiKo,

We have a Pull Request adding a translation of our gender-neutral restroom signs.

Might either of you be able to offer feedback on this translation?

From :
> This is a gender-neutral bathroom.
>
> It's for everyone.

to :

> Ceci est une salle de bain non genrée.
> 
> Tout le monde y a accès.

Thank you.

\- DeeDeeG

**Comment by DeeDeeG** [comment]
I took a look at this closely, using [Wiktionary](https://wiktionary.org) and [Google Translate](https://translate.google.com) to help.

As far as I can tell, the literal translation is something like this:

> This is a non-gendered bathroom.
>
> Everyone has access to it.

So that seems at least literally accurate to convey the meaning of the PDF sign. If there are no reviews from native speakers soon, I am comfortable merging this as-is. Will wait a few days to make sure there is an opportunity for comments to come in, but in general, I do plan on merging soon.

Thanks again.

\- DeeDeeG

**Comment by DeeDeeG** [comment]
Merging without review from a second French language speaker, since it's a small amount of text that can be reviewed pretty easily with Wiktionary and Google Translate.

TODO is to make the site serve these PDFs wen viewing in French, or else add these PDFs to the page regardless, i.e. make PDF signs with multiple languages available regardless of language being viewed.

**Comment by BertrandClosset** [comment]
Hi @DeeDeeG,
I'm arriving a little bit late, sorry.
I just checked the translation it's alright for me

Have a nice day !

Bertrand

**Comment by DeeDeeG** [comment]
@BertrandClosset no problem, and thank you!

**Pull request merged**
