### PR TITLE
Listofpopularcities 79 rsid

### PR DESCRIPTION
**Pull request by RSid**
closes issue #79

### CODE REVIEW

**Comment by RSid** [comment]
Presuming the front end styling is ok, I think this is good to go!

**Comment by tkwidmer** [comment]
I think we should do more on the front end. Like having each listing link to the search for the city center of that city. But ill go ahead and merge this.

**Comment by RSid** [comment]
@tkwidmer , the listings do actually link to searches for the city center of that city already - sorry, I guess they don't visually look much like links. Would it help clarify that if I added link underlining back in or something?

**Comment by tkwidmer** [comment]
oh, thats fine then. I may end up changing the visual style a little bit. But yeah. thanks for doing this!

**Comment by RSid** [comment]
No worries! I enjoyed it. But yeah, I'm not terribly UX-y, go for it.

**Pull request merged**
