### PR TITLE
Adjust padding at sides of pages, space out the submit new restroom page a bit

### LINKED ISSUE #273: Strange UI on iOS App
I just downloaded the Refuge Restrooms iOS App and went to check out the submit page. I think it might look nicer if there was a little bit of a margin before the different fields on the left!

### PR DESCRIPTION
**Pull request by DeeDeeG**
# Context
- Fixes #273 
- Addresses padding on the left/right, also doing some vertical spacing tweaks.

# Summary of Changes

- Trying to address horizontal padding on submit new restroom page
- Vertical spacing changes to the new restroom page (looks nicer?)
- Vertical spacing change to the Contact page (looks nicer?)

# Screenshots

## Before

before

## After

after

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Not ready to merge yet.

I'm kind of in over my head with this at the moment. I'm installing Vagrant as I type, to see what that's all about. So maybe I can figure out where to go from here. Still, I wanted to put up where I've gotten so far in a PR.

**Comment by DeeDeeG** [comment]
Deleting the global rule (about not having left/right padding at small screen sizes): would positively affect some pages :white_check_mark:, but would negatively affect some pages :x:. Can't really do anything about it without the ability to edit both CSS and HTML, so I'm trying to set up Vagrant and see if I can figure out how to edit the HTML properly. More details below.

It turns out there are different pages handling this differently from one-another. Three categories:

- "Submit New Restroom" (which I focused on in this PR as of the moment) deserves a bit of left-right padding. Easy to add in a way specific to this page via CSS. So that's what commits here so far have done.
  - "Contact" is equivalent to "Submit New Restroom" in that regard, but I haven't addressed it yet.
    - Both have text input boxes that reach the edges of the screen at small screen sizes, and **would benefit from always having a minimum amount of padding**

- "Restrooms" (the search results page) is set up in such a way that it definitely needs no padding on the left or right, at small screen-sizes, whereas the other pages could have it or not have it and still work. Search results get very scrunched (still usable) at around 280 pixels screen-width. So I'd hate to scrunch it more with the padding. **needs to not receive padding at small screen sizes**

- "About REFUGE" has a div with left-right padding on it (`<div style="padding-left: 25px; padding-right: 25px;"></div>`) regardless of screen size.
  - "Download Unisex Restroom Signs" also does this (`<div style="so-and-so">`).
    - Both also have progressively larger padding applied via global rules measuring screen-size, at the moment, (wider screen=wider padding), and **these are flexible, but look a bit worse with added padding**.

Known Unaffected pages:

- The Homepage doesn't have a `main > div.container` structure, so none of this applies
- "Public API" page is very much its own thing, and none of this applies

**Comment by DeeDeeG** [comment]
I'm glad I decided to type all that out.

So at the end of the day, it seems like just being page-specific can make this doable. I can leave the tricky pages alone, because they are the ones that already work fine.

"New Restroom" is already done. All that's left would seem to be updating the "Contact" page.

**Comment by DeeDeeG** [comment]
Tested now, all is working as intended.

**Comment by DeeDeeG** [comment]
CC @tkwidmer, this is more or less ready to merge, and I welcome any comments.

Notes:

- There is a tiny vertical spacing change in the Contact page, 10 added pixels between the "Contact" heading and the actual text input fields. I think it's a slight improvement, but can remove if anyone prefers it the old way. Used the "headroom" style already baked into the project.

- New-restroom page has some slightly more-custom vertical spacing. 

- The guess-button and the nearby-restrooms container have really custom margin-top and margin-bottom, so these would be the first things to change if custom stuff needs to be reduced.

- Lastly, I'm not able to test in vagrant whether the "div.nearby-container" styles I tried to use work perfectly, because they need Google Maps API access to test.  It looks okay when I re-implement it in my Firefox dev tools off of the live instance of refugerestrooms.org.

- I have tested and confirmed that only new restroom page and contact page are changed by these commits.

I can try to use less custom stuff and use built-in styles such as "headroom" "more-headroom" etc. But I'm pretty happy with the look at the moment. (Glad to have any comments on this)

Using the built-in "headroom" (`margin-top: 20px`) style would be closest to what I have here in two places (`margin-top: 32px`).

(If using built-in styles is important to the project, and the spacing I picked is preferred, it might be nice to add a 32px tall headroom style, called "32-pixel-headroom" or "fancy-headroom". Right now there's min-headroom 10px, headroom 20px, more-headroom 40px, even-more-headroom 60px.)

**Comment by DeeDeeG** [comment]
I made a simpler version of this PR on another branch. I cleaned up the commits a lot. Also removed everything except the two changes discussed in #273.

https://github.com/RefugeRestrooms/refugerestrooms/compare/develop...DeeDeeG:DeeDeeG-fix-padding-and-margins

**Comment by DeeDeeG** [comment]
The build failing just has to do with the Google Maps API error. 

It fails to search "Winnipeg" from the splash page because the Maps API is unhappy about referral URLs and won't work on localhost, apparently?

**Comment by mi-wood** [comment]
Thanks @DeeDeeG! I'm going to go ahead and merge this. I'll take a look at fixing the google maps issue in the tests.

**Comment by mi-wood** [comment]
Ugh, thought we had squash commits only on. Turned it on now, so this will always get combined into a single commit when merged in the future.

**Comment by DeeDeeG** [comment]
Hi @mi-woood. Thanks for merging.

This was my first PR here, and I learned a bit while I was making this, and since then. This PR wasn't really in a state I'd call up to my normal standards, when merged. I should have cleaned it up. Some of the changes weren't tested thoroughly, so I'll be double-checking what they look like now. But also I think the commits look sloppy, their commit messages are redundant and not very helpful, and there needn't be 13 commits for so few changes.

Do you think this could be backed out, in favor of the more minimal changes here?: https://github.com/RefugeRestrooms/refugerestrooms/compare/develop...DeeDeeG:DeeDeeG-fix-padding-and-margins

Or would you prefer any problems just be addressed the usual way, without backing out the merge?

Backing out the merge would be something like this, on command line:
- `git clone https://github.com/RefugeRestrooms/refugerestrooms`
- `cd refugerestrooms`
- git reset --hard [2a75710a4fd1f602357b9f07758ab96a54c5406e](https://github.com/RefugeRestrooms/refugerestrooms/commit/2a75710a4fd1f602357b9f07758ab96a54c5406e)
- `git push -f` to force this reset version to github
- going onto github and re-accepting the PR for [`mention-contributing-in-readme`](https://github.com/RefugeRestrooms/refugerestrooms/pull/324)
- and then accepting a PR for the cleaner more minimal version of this?

**Comment by DeeDeeG** [comment]
Okay, so I took a look, and yes the styling looks okay. Maybe I also over-reacted a bit to the untidiness of the commits.

C'est la vie! I can deal with it.

**Comment by DeeDeeG** [comment]
This is definitely fine merged as-is, but would you be interested in backing out the merge, and doing it over? I could do a PR with the same file changes, but done in fewer, more-logically-organized commits, with more understandable commit messages.

I think the current ones are kind of confusing. A lot of them partly undo each-other, and reading through 13 commits to figure out what changed is obviously harder than reading through 4 or 5.

It's not a huge thing, whether it gets backed out or not, but it would be much easier to back it out now compared to than further down the road. I'll leave it up to core maintainers whether to do it or not.

**Comment by DeeDeeG** [comment]
If it should be backed out, I would be envisioning these steps in the command line:
- `cd ~; mkdir refuge-reset ; cd refuge-reset`
to make a fresh environment to work in, in current user's home directory
- `git clone https://github.com/RefugeRestrooms/refugerestrooms/ && cd refugerestrooms`
to be sure that things are aligned with the latest develop branch
- `git reset --hard 2a75710a4fd1f602357b9f07758ab96a54c5406e`, 
which resets to when this https://github.com/RefugeRestrooms/refugerestrooms/commit/2a75710a4fd1f602357b9f07758ab96a54c5406e was the most recent commit. Basically it just vanishes away the last two pull requests, which were both my PRs.
- `git push -f`
To push this to GitHub, overwriting the develop branch on GitHub with one reset to tkwidmer's latest commit. 
I could then re-create my two pull requests, or someone can simply re-open them if GitHub can do that... and they could be merged.)

**Comment by mi-wood** [comment]
@DeeDeeG I originally merged thinking I set the squash commit setting correctly. I'd prefer not to force reset a remote base branch. Is there any reason other than commit history to fix this? Otherwise you can submit another PR to clean it up.

**Comment by DeeDeeG** [comment]
Nope, no strong reason but the commit history being neatened up.

One actual thing I'm on the fence about in this PR is the vertical margins. I might be interested in opening up an issue to ask for general feedback on the margin-top and margin-bottom added here, since there is a lot of it. If folks would be interested in commenting on the design changes that would be great.

**Pull request merged**
